
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tddobkuhizsdoevgiebl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkZG9ia3VoaXpzZG9ldmdpZWJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NTAwMjksImV4cCI6MjA1OTUyNjAyOX0.Ey9_O0K4MGYkwlPjqvqdEtMJ60A7Ht_EP739iTeEXWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      fetch: fetch.bind(globalThis),
    },
  }
);
